/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SkillCategory = {
  _id: string;
  _type: "skillCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  orderIndex?: number;
  skills?: Array<string>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  orderIndex?: number;
  type?: string;
  status?: "active" | "completed" | "in-development";
  year?: string;
  screenshot?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortDescription?: string;
  longDescription?: string;
  tags?: Array<string>;
  deployedUrl?: string;
  githubUrl?: string;
  impactStats?: Array<{
    value?: string;
    label?: string;
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  profilePhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  role?: string;
  roleEmphasis?: string;
  bio?: string;
  bioEmphasis?: string;
  basedIn?: string;
  status?: string;
  education?: string;
  focus?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  title?: string;
  metaDescription?: string;
  heroTagline?: string;
  heroSubtitle?: string;
  availabilityText?: string;
  email?: string;
  githubUrl?: string;
  linkedinUrl?: string;
  contactHeadline?: string;
  contactSubhead?: string;
  avgResponse?: string;
  location?: string;
  openTo?: Array<string>;
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SkillCategory
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | About
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    name,    title,    metaDescription,    heroTagline,    heroSubtitle,    availabilityText,    email,    githubUrl,    linkedinUrl,    contactHeadline,    contactSubhead,    avgResponse,    location,    openTo,    favicon  }
export type SiteSettingsQueryResult = {
  name: string | null;
  title: string | null;
  metaDescription: string | null;
  heroTagline: string | null;
  heroSubtitle: string | null;
  availabilityText: string | null;
  email: string | null;
  githubUrl: string | null;
  linkedinUrl: string | null;
  contactHeadline: string | null;
  contactSubhead: string | null;
  avgResponse: string | null;
  location: string | null;
  openTo: Array<string> | null;
  favicon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: aboutQuery
// Query: *[_type == "about"][0] {    profilePhoto,    role,    roleEmphasis,    bio,    bioEmphasis,    basedIn,    status,    education,    focus  }
export type AboutQueryResult = {
  profilePhoto: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  role: string | null;
  roleEmphasis: string | null;
  bio: string | null;
  bioEmphasis: string | null;
  basedIn: string | null;
  status: string | null;
  education: string | null;
  focus: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: projectsQuery
// Query: *[_type == "project"] | order(orderIndex asc) {    _id,    title,    slug,    orderIndex,    type,    status,    year,    screenshot,    shortDescription,    longDescription,    tags,    deployedUrl,    githubUrl,    impactStats  }
export type ProjectsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  orderIndex: number | null;
  type: string | null;
  status: "active" | "completed" | "in-development" | null;
  year: string | null;
  screenshot: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  shortDescription: string | null;
  longDescription: string | null;
  tags: Array<string> | null;
  deployedUrl: string | null;
  githubUrl: string | null;
  impactStats: Array<{
    value?: string;
    label?: string;
    _key: string;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: skillCategoriesQuery
// Query: *[_type == "skillCategory"] | order(orderIndex asc) {    _id,    title,    orderIndex,    skills  }
export type SkillCategoriesQueryResult = Array<{
  _id: string;
  title: string | null;
  orderIndex: number | null;
  skills: Array<string> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: homePageQuery
// Query: {  "settings":   *[_type == "siteSettings"][0] {    name,    title,    metaDescription,    heroTagline,    heroSubtitle,    availabilityText,    email,    githubUrl,    linkedinUrl,    contactHeadline,    contactSubhead,    avgResponse,    location,    openTo,    favicon  },  "about":   *[_type == "about"][0] {    profilePhoto,    role,    roleEmphasis,    bio,    bioEmphasis,    basedIn,    status,    education,    focus  },  "projects":   *[_type == "project"] | order(orderIndex asc) {    _id,    title,    slug,    orderIndex,    type,    status,    year,    screenshot,    shortDescription,    longDescription,    tags,    deployedUrl,    githubUrl,    impactStats  },  "skills":   *[_type == "skillCategory"] | order(orderIndex asc) {    _id,    title,    orderIndex,    skills  }}
export type HomePageQueryResult = {
  settings: {
    name: string | null;
    title: string | null;
    metaDescription: string | null;
    heroTagline: string | null;
    heroSubtitle: string | null;
    availabilityText: string | null;
    email: string | null;
    githubUrl: string | null;
    linkedinUrl: string | null;
    contactHeadline: string | null;
    contactSubhead: string | null;
    avgResponse: string | null;
    location: string | null;
    openTo: Array<string> | null;
    favicon: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  about: {
    profilePhoto: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    role: string | null;
    roleEmphasis: string | null;
    bio: string | null;
    bioEmphasis: string | null;
    basedIn: string | null;
    status: string | null;
    education: string | null;
    focus: string | null;
  } | null;
  projects: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    orderIndex: number | null;
    type: string | null;
    status: "active" | "completed" | "in-development" | null;
    year: string | null;
    screenshot: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    shortDescription: string | null;
    longDescription: string | null;
    tags: Array<string> | null;
    deployedUrl: string | null;
    githubUrl: string | null;
    impactStats: Array<{
      value?: string;
      label?: string;
      _key: string;
    }> | null;
  }>;
  skills: Array<{
    _id: string;
    title: string | null;
    orderIndex: number | null;
    skills: Array<string> | null;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0] {\n    name,\n    title,\n    metaDescription,\n    heroTagline,\n    heroSubtitle,\n    availabilityText,\n    email,\n    githubUrl,\n    linkedinUrl,\n    contactHeadline,\n    contactSubhead,\n    avgResponse,\n    location,\n    openTo,\n    favicon\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "about"][0] {\n    profilePhoto,\n    role,\n    roleEmphasis,\n    bio,\n    bioEmphasis,\n    basedIn,\n    status,\n    education,\n    focus\n  }\n': AboutQueryResult;
    '\n  *[_type == "project"] | order(orderIndex asc) {\n    _id,\n    title,\n    slug,\n    orderIndex,\n    type,\n    status,\n    year,\n    screenshot,\n    shortDescription,\n    longDescription,\n    tags,\n    deployedUrl,\n    githubUrl,\n    impactStats\n  }\n': ProjectsQueryResult;
    '\n  *[_type == "skillCategory"] | order(orderIndex asc) {\n    _id,\n    title,\n    orderIndex,\n    skills\n  }\n': SkillCategoriesQueryResult;
    '\n{\n  "settings": \n  *[_type == "siteSettings"][0] {\n    name,\n    title,\n    metaDescription,\n    heroTagline,\n    heroSubtitle,\n    availabilityText,\n    email,\n    githubUrl,\n    linkedinUrl,\n    contactHeadline,\n    contactSubhead,\n    avgResponse,\n    location,\n    openTo,\n    favicon\n  }\n,\n  "about": \n  *[_type == "about"][0] {\n    profilePhoto,\n    role,\n    roleEmphasis,\n    bio,\n    bioEmphasis,\n    basedIn,\n    status,\n    education,\n    focus\n  }\n,\n  "projects": \n  *[_type == "project"] | order(orderIndex asc) {\n    _id,\n    title,\n    slug,\n    orderIndex,\n    type,\n    status,\n    year,\n    screenshot,\n    shortDescription,\n    longDescription,\n    tags,\n    deployedUrl,\n    githubUrl,\n    impactStats\n  }\n,\n  "skills": \n  *[_type == "skillCategory"] | order(orderIndex asc) {\n    _id,\n    title,\n    orderIndex,\n    skills\n  }\n\n}\n': HomePageQueryResult;
  }
}
