import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Your Name',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'title',
      title: 'Page Title (SEO)',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'metaDescription',
      title: 'Meta Description (SEO)',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'heroTagline',
      title: 'Hero Tagline',
      description: 'The phrase shown after the wave animation, e.g. "I build intelligent systems."',
      type: 'string',
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Hero Subtitle',
      description: 'Shown at bottom of hero, e.g. "CS student · AI & ML · VVCE"',
      type: 'string',
    }),
    defineField({
      name: 'availabilityText',
      title: 'Availability Text',
      description: 'Shown in the hero eyebrow, e.g. "Available for opportunities · 2026"',
      type: 'string',
    }),
    defineField({
      name: 'email',
      title: 'Contact Email',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'githubUrl',
      title: 'GitHub URL',
      type: 'url',
    }),
    defineField({
      name: 'linkedinUrl',
      title: 'LinkedIn URL',
      type: 'url',
    }),
    defineField({
      name: 'contactHeadline',
      title: 'Contact Headline',
      description: 'The big CTA text, e.g. "Let\'s build something great."',
      type: 'text',
      rows: 2,
    }),
    defineField({
      name: 'contactSubhead',
      title: 'Contact Subheading',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'avgResponse',
      title: 'Average Response Time',
      type: 'string',
      initialValue: '24h',
    }),
    defineField({
      name: 'location',
      title: 'Location',
      type: 'string',
      initialValue: 'India',
    }),
    defineField({
      name: 'openTo',
      title: 'Open To',
      description: 'List of opportunity types',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'favicon',
      title: 'Favicon Image',
      description: 'Upload your square favicon logo image (will override the default nagslogo.jpeg)',
      type: 'image',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'dockAboutUrl',
      title: 'Dock: About URL / Route',
      description: 'The link or route for the About icon in the floating dock (defaults to /about)',
      type: 'string',
      initialValue: '/about',
    }),
    defineField({
      name: 'dockWorkUrl',
      title: 'Dock: Work URL / Route',
      description: 'The link or route for the Work icon in the floating dock (defaults to /work)',
      type: 'string',
      initialValue: '/work',
    }),
    defineField({
      name: 'dockEmail',
      title: 'Dock: Email Address',
      description: 'The email address for the Email icon in the floating dock (e.g. nagias612@gmail.com)',
      type: 'string',
      initialValue: 'nagias612@gmail.com',
    }),
    defineField({
      name: 'dockLinkedinUrl',
      title: 'Dock: LinkedIn URL',
      description: 'The URL for the LinkedIn icon in the floating dock (e.g. https://linkedin.com/in/nagendraas612)',
      type: 'string',
      initialValue: 'https://linkedin.com/in/nagendraas612',
    }),
    defineField({
      name: 'dockGithubUrl',
      title: 'Dock: GitHub URL',
      description: 'The URL for the GitHub icon in the floating dock (e.g. https://github.com/Nagendraas612)',
      type: 'string',
      initialValue: 'https://github.com/Nagendraas612',
    }),
    defineField({
      name: 'footerCopyright',
      title: 'Footer Copyright Text',
      description: 'The copyright text shown at the bottom of the page (e.g. © 2026 Nagendra AS)',
      type: 'string',
      initialValue: '© 2026 Nagendra AS',
    }),
  ],
  preview: {
    select: { title: 'name' },
  },
})
